# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Storyblocks Design System
email: Kyhry@Storyblocks.com
description: > # this means to ignore newlines until "baseurl:"
  This site aims to provide everything you need to get up to speed quickly when designing for Storyblocks.
baseurl: "/design-system" # the subpath of your site, e.g. /blog
url: "https://storyblocks.github.io/design-system/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Setup pattern collection
collections:
  patterns:
    output: true

# Overriding default colors
branding:
  logo_path: '/assets/logo.svg'
  navigation_background_color: '#ffffff'
  navigation_link_color: '#666666'
  navigation_link_color_hover: 'gray'
  main_background_color: '#F5F5F5'
